# 2.1 ndarray

## 1. ndarray的特性

### 多维性

In [1]:
import numpy as np

In [2]:
arr = np.array(5)
print(arr)
print('arr的维度：', arr.ndim)

5
arr的维度： 0


In [3]:
arr = np.array([1, 2, 3])
print(arr)
print('arr的维度：', arr.ndim)

[1 2 3]
arr的维度： 1


In [5]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr)
print('arr的维度：', arr.ndim)

[[1 2 3]
 [4 5 6]]
arr的维度： 2


### 同质性

In [6]:
arr = np.array([1, 'hello'])
print(arr)

['1' 'hello']


In [7]:
arr = np.array([1, 2.5, 3])
print(arr)

[1.  2.5 3. ]


## 2. ndarray的属性

In [8]:
arr = np.array(1)
print(arr)
print('数组的形状：', arr.shape)
print('数组的维度：', arr.ndim)
print('元素的个数：', arr.size)
print('数组的数据类型：', arr.dtype)
print('元素的转置：', arr.T)

1
数组的形状： ()
数组的维度： 0
元素的个数： 1
数组的数据类型： int64
元素的转置： 1


In [9]:
arr = np.array([1, 2.5, 3])
print(arr)
print('数组的形状：', arr.shape)
print('数组的维度：', arr.ndim)
print('元素的个数：', arr.size)
print('数组的数据类型：', arr.dtype)
print('元素的转置：', arr.T)

[1.  2.5 3. ]
数组的形状： (3,)
数组的维度： 1
元素的个数： 3
数组的数据类型： float64
元素的转置： [1.  2.5 3. ]


In [10]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr)
print('数组的形状：', arr.shape)
print('数组的维度：', arr.ndim)
print('元素的个数：', arr.size)
print('数组的数据类型：', arr.dtype)
print('元素的转置：', arr.T)

[[1 2 3]
 [4 5 6]]
数组的形状： (2, 3)
数组的维度： 2
元素的个数： 6
数组的数据类型： int64
元素的转置： [[1 4]
 [2 5]
 [3 6]]


## 3. ndarray的创建

In [11]:
# 基础的创建方法
list1 = [1, 2, 3]
arr = np.array(list1, dtype=np.float64)
print(arr.ndim)
print(arr)

1
[1. 2. 3.]


In [12]:
# copy
arr1 = np.copy(arr) # 元素跟原始的数据相同，但是不是一个数组了
print(arr1)
arr1[0] = 8
print(arr1)
print(arr)

[1. 2. 3.]
[8. 2. 3.]
[1. 2. 3.]


In [13]:
# 预定义形状
arr = np.zeros((2, 3), dtype=int)
print(arr)
print(arr.dtype)

[[0 0 0]
 [0 0 0]]
int64


In [15]:
arr = np.zeros((200,), dtype=int)
print(arr)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]


In [16]:
# 全1
arr = np.ones((5, 8), dtype=int)
print(arr)

[[1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]]


In [18]:
# 未初始化
arr = np.empty((2, 3), dtype=int)
print(arr)

[[0 0 0]
 [0 0 0]]


In [19]:
arr = np.full((3, 4), 2025)
print(arr)

[[2025 2025 2025 2025]
 [2025 2025 2025 2025]
 [2025 2025 2025 2025]]


In [21]:
arr1 = np.zeros_like(arr)
print(arr1)
print('-' * 20)

arr1 = np.empty_like(arr)
print(arr1)
print('-' * 20)

arr1 = np.ones_like(arr)
print(arr1)
print('-' * 20)

arr1 = np.full_like(arr, 2027)
print(arr1)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
--------------------
[[2027 2027 2027 2027]
 [2027 2027 2027 2027]
 [2027 2027 2027 2027]]
--------------------
[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]
--------------------
[[2027 2027 2027 2027]
 [2027 2027 2027 2027]
 [2027 2027 2027 2027]]


In [24]:
# 等差数列：2 4 6 8 10 12
arr = np.arange(2, 51, 2)
print(arr)

[ 2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48
 50]


In [25]:
# 等间隔数列
arr = np.linspace(0, 100, 5)
print(arr)

[  0.  25.  50.  75. 100.]


In [26]:
arr = np.linspace(0, 100, 5, dtype=int)
print(arr)
print('-' * 20)

arr = np.arange(0, 101, 25)
print(arr)

[  0  25  50  75 100]
--------------------
[  0  25  50  75 100]


In [27]:
# 对数间隔数列
arr = np.logspace(0, 4, 3, base=2)
print(arr)

[ 1.  4. 16.]


In [28]:
arr = np.linspace(0,4,3)
print(arr)

[0. 2. 4.]


In [29]:
arr = np.logspace(0,4,3)
print(arr)

[1.e+00 1.e+02 1.e+04]


In [30]:
# 特殊矩阵
# 单位矩阵：主对角线上的数字为1， 其它的数字为0
arr = np.eye(3, 4, dtype=int)
print(arr)

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]]


In [31]:
# 对角矩阵：主对角线上非零的0，其它的数字为0
arr = np.diag([5, 1, 2, 3])
print(arr)

[[5 0 0 0]
 [0 1 0 0]
 [0 0 2 0]
 [0 0 0 3]]


In [33]:
# 随机数组的生成
# 生成0到1之间的随机浮点数（均匀分布）
arr = np.random.randn(2, 3)
print(arr)

[[ 0.63189019 -0.02712345  1.70420619]
 [ 0.21088984 -1.11752488  0.67811641]]


In [34]:
# 生成指定范围区间的随机浮点数
arr = np.random.uniform(3, 6, (2, 3))
print(arr)

[[3.21399134 4.99958858 5.36119099]
 [5.97432585 3.66681524 3.76777428]]


In [35]:
# 生成指定范围区间的随机整数
arr = np.random.randint(3, 20, (2, 3))
print(arr)

[[18 15 19]
 [16  8  3]]


In [36]:
# 生成随机数列（正态分布）（-3到3之间）
# 两边小，中间大
arr = np.random.randn(2, 3)
print(arr)

[[ 0.2328792   0.57942815 -2.21782924]
 [ 0.85930312  1.27739771 -0.58205323]]


In [37]:
# 设置随机种子
np.random.seed(20)
arr = np.random.randint(1, 10, (2, 5))
print(arr)

[[4 5 7 8 3]
 [1 7 9 6 4]]


## 4. ndarray的数据类型

### 布尔类型 bool
### 整数类型 int uint
### 浮点数 float
### 复数 complex

In [38]:
arr = np.array([1, 0, 127, 0], dtype=bool)
print(arr)

arr = np.array([1, 0, 127, 0], dtype=np.int8)
print(arr)

arr = np.array([1, 2, 3], dtype='i8')
print(arr)

[ True False  True False]
[  1   0 127   0]
[1 2 3]


## 5. 索引与切片

In [39]:
# 一维数组的索引与切片
arr = np.random.randint(1, 100, 20)
print(arr)

[17 63 17  8 99  7 27 14 76 59 26  4 75 76 62 78 84 58 95 33]


In [40]:
print(arr[10])
print(arr[:])   # 获取全部
print(arr[2:5])
print(arr[slice(2, 15, 3)])
print(arr[(arr>10) & (arr < 70)])

26
[17 63 17  8 99  7 27 14 76 59 26  4 75 76 62 78 84 58 95 33]
[17  8 99]
[17  7 76  4 62]
[17 63 17 27 14 59 26 62 58 33]


In [43]:
# 二维数组的索引与切片
arr = np.random.randint(1,100,(4,8))
print(arr)
print('-' * 20)

print(arr[1,3])  # 索引
print(arr[1,2:5])
print(arr[2][arr[2] > 50])
print(arr[:,3])

[[24 53 97 77 79 96 55 82]
 [74 28 40 88 10 15 32 57]
 [57 59 80 28 51 75 70  3]
 [58 24 96 26 42 10 67 16]]
--------------------
88
[40 88 10]
[57 59 80 51 75 70]
[77 88 28 26]


## 6. ndarry的运算

In [44]:
# 算数运算
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print(a + b)
print(a - b)
print(a * b)
print(a / b)
print(a ** 2)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]
[1 4 9]


In [45]:
c = [1, 2, 3]
d = [4, 5, 6]
for i in range(len(c)):
    d[i] = c[i] + d[i]
print(d)

[5, 7, 9]


In [47]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
b = np.array([[4, 5, 6], [7, 8, 9], [10, 11, 12]])
print(a + b)
print('-' * 20)

print(a - b)
print('-' * 20)

print(a * b)
print('-' * 20)

print(a / b)
print('-' * 20)

print(a ** 2)

[[ 5  7  9]
 [11 13 15]
 [17 19 21]]
--------------------
[[-3 -3 -3]
 [-3 -3 -3]
 [-3 -3 -3]]
--------------------
[[  4  10  18]
 [ 28  40  54]
 [ 70  88 108]]
--------------------
[[0.25       0.4        0.5       ]
 [0.57142857 0.625      0.66666667]
 [0.7        0.72727273 0.75      ]]
--------------------
[[ 1  4  9]
 [16 25 36]
 [49 64 81]]


In [48]:
# 数组与标量之间的算术运算
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a + 3)
print(a * 3)

[[ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[ 3  6  9]
 [12 15 18]
 [21 24 27]]


In [49]:
# 广播机制: 1.获取形状 2.是否可广播
# 同一维度：相同、1
a = np.array([1,2,3]) #1*3
b = np.array([[4],[5],[6]])  #3*1
print(b - a )
'''a
 1 2 3
 1 2 3
 1 2 3
 b
 4 4 4
 5 5 5
 6 6 6
'''

[[3 2 1]
 [4 3 2]
 [5 4 3]]


'a\n 1 2 3\n 1 2 3\n 1 2 3\n b\n 4 4 4\n 5 5 5\n 6 6 6\n'

In [ ]:
# 错误的例子
a = np.array([1,2,3]) #1*3
b = np.array([4,5])  #1*2
print(b - a)

In [51]:
# 矩阵运算
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
b = np.array([[4,5,6],[7,8,9],[1, 2,3]])
print(a @ b)

[[ 21  27  33]
 [ 57  72  87]
 [ 93 117 141]]


In [ ]:
'''
a
1 2 3
4 5 6
7 8 9

b
4 5 6
7 8 9

1 2 3
'''

# 2.3 numpy中的常用函数

## 1. 基本数学函数

In [52]:
# 计算平方根
print(np.sqrt(9))
print(np.sqrt([1,4,9]))
arr = np.array([1,25,81])
print(np.sqrt(arr))

3.0
[1. 2. 3.]
[1. 5. 9.]


In [53]:
# 计算指数
print(np.exp(1))

2.718281828459045


In [54]:
# 计算自然对数
print(np.log(2.71))

0.9969486348916096


In [56]:
# 计算正弦值、余弦值
print(np.sin(np.pi/2))
print(np.cos(np.pi))

1.0
-1.0


In [57]:
# 计算绝对值
arr = np.array([-1, 1, 2, -3])
print(np.abs(arr))

[1 1 2 3]


In [58]:
# 计算a的b次幂
print(np.power(arr, 3))

[ -1   1   8 -27]


In [59]:
# 四舍五入
print(np.round([3.2, 43.5, 8.1, 9.6]))

[ 3. 44.  8. 10.]


In [60]:
# 向上取整、向下取整
arr = np.array([1.6, 25.1, 81.7])
print(np.ceil(arr))
print(np.floor(arr))

[ 2. 26. 82.]
[ 1. 25. 81.]


In [61]:
# 检测缺失值
np.isnan([1, 2, np.nan, 3])

array([False, False,  True, False])

## 2. 统计函数

### 求和、计算平均值、计算中位数、标准差、方差
### 查找最大值、最小值
### 计算份位数、累积值、累积差

In [62]:
arr = np.random.randint(1, 200, 8)
print(arr)

[119 194  31  89  50 169 140  70]


In [63]:
# 求和
print(np.sum([1, 2, 3]))

6


In [64]:
# 计算平均值
print(np.mean(arr))

107.75


In [65]:
# 计算中位数
# 奇数：排序后中间的数值
# 偶数：中间的两个数的平均值
print(np.median([4,1,2]))
print(np.median([1,1,1,1,1,1,1,1,100]))

2.0
1.0


In [66]:
# 计算标准差、方差
# 1，2，3的平均值2
# ((102)^2 + (2-2)^2 + (3-2)^2) / 3 = 0.66
arr1 = np.array([1,2,1,2,1,1,1,2])
arr2 = np.array([1,0,3,0,0,0,4,3])
print(np.mean(arr1))
print(np.mean(arr2))
print(np.var(arr1))
print(np.var(arr2))

1.375
1.375
0.234375
2.484375


In [67]:
# 计算最大值、最小值
print(arr)
print(np.max(arr), np.argmax(arr))
print(np.min(arr), np.argmin(arr))

[119 194  31  89  50 169 140  70]
194 1
31 2


In [70]:
# 分位数
# 中位数
# --------
# 1     2       3       4
# 1         2           3
print(np.median([1,2,3]))
print(np.median([1,2,3,4]))
np.random.seed(0)
arr = np.random.randint(0, 100, 4)
print(arr)
# __________________
print('-' * 20)
# 44   47   64   67
# (47+64)/2
print(np.median(arr))
print(np.percentile(arr,80))
# 0.25*3=0.75
# (47-44)*0.75=2.25 + 44 = 46.25
# 3*0.8 = 2.4
# (67-64)*0.4 = 1.2 + 64 = 65.2

2.0
2.5
[44 47 64 67]
--------------------
55.5
65.2


In [71]:
# 累积和、累积积
arr = np.array([1, 2, 3])
print(np.sum(arr))
print(np.cumsum(arr))
print(np.cumprod(arr))

6
[1 3 6]
[1 2 6]
